### PR TITLE
1

### PR DESCRIPTION
**Pull request by slack909**

### CODE REVIEW

**Comment by luk1337** [comment]
lol

**Comment by slack909** [comment]
Add strings.xml for manual settings network.
13 мая 2016 г. 21:23 пользователь "LuK" notifications@github.com написал:

**Comment by luk1337** [comment]
Why should I?

**Comment by slack909** [comment]
For example. Stock firmware has choise wcdma only and lte only. Many cm
device already has it. It usefull. I copy it from another cm 13 device. Now
compile and it work.
14 мая 2016 г. 1:14 пользователь "LuK" notifications@github.com написал:

**Comment by luk1337** [comment]
> Many cm device already has it. It usefull.

Could you list some of them?

**Comment by slack909** [comment]
Just search in github cyanogenmode 'strings.xml' . really many.
14 мая 2016 г. 1:18 пользователь "LuK" notifications@github.com написал:

**Comment by luk1337** [comment]
Welp, that's not helpful at all...

**Pull request closed without merging**
